In [1]:
import pandas as pd
import numpy as np
import math
import csv

In [3]:
def flat_list(ri, ci):
    flat_list = []
    flat_list.append(0)
    for r in range(ri-3, ri+4):
        for c in range(ci-3, ci+4):
            flat_list.append(B[c, r])    
    return flat_list

In [ ]:
for m in [3, 96, 100]:
    try:
        C=pd.read_csv('label0ivat%d.csv' %m, header=None)  #labels
        a = pd.read_excel('iVat%d.xlsx' %m, header = None)
        A = np.array(a)
        rows = A.shape[0]
        cols = A.shape[1]
        maxValue = np.amax(A)
        minValue = np.amin(A)
        for x in range(cols):
            for y in range(rows):
                A[x,y]=math.ceil(((A[x,y]-minValue)/(maxValue-minValue))*255) ### Normalization

        B=np.pad(A, ((3,3),(3,3)), 'constant',constant_values=255)####Padding

        cord = C.to_numpy()

        data = []

        for i in range(len(cord)):
            c = cord[i][0]
            #if(c!=1):    # to correct coords for label1
            #    c-=1     # to correct coords for label1
            r = cord[i][1]
            data.append(flat_list(r-1+3, c-1+3))  # to include python indexing and padding shift

        with open("feat_vect_0.csv", 'a', newline="") as f:
            writer = csv.writer(f)
            writer.writerows(data)
        
    except:
        continue

In [2]:
        def flat_list(ri, ci):
            flat_list = []
            flat_list.append(0)
            for r in range(ri-3, ri+4):
                for c in range(ci-3, ci+4):
                    flat_list.append(B[c, r])    
            return flat_list


        C=pd.read_csv('Zeroesofivat13(1).csv', header=None)  #coordinates
        a = pd.read_csv('iVAT13.csv', header = None) #ivat image
        A = np.array(a)
        rows = A.shape[0]
        cols = A.shape[1]
        maxValue = np.amax(A)
        minValue = np.amin(A)
        for x in range(cols):
            for y in range(rows):
                A[x,y]=math.ceil(((A[x,y]-minValue)/(maxValue-minValue))*255) ### Normalization

        B=np.pad(A, ((3,3),(3,3)), 'constant',constant_values=255)####Padding

        cord = C.to_numpy()

        data = []

        for i in range(len(cord)):
            c = cord[i][0]
            #if(c!=1):    # to correct coords for label1
            #    c-=1     # to correct coords for label1
            r = cord[i][1]
            data.append(flat_list(r-1+3, c-1+3))  # to include python indexing and padding shift

        with open("ivat13labels0.csv", 'a', newline="") as f:
            writer = csv.writer(f)
            writer.writerows(data)

FileNotFoundError: [Errno 2] File b'Zeroesofivat13(1).csv' does not exist: b'Zeroesofivat13(1).csv'

In [12]:
c

1

In [21]:
[r[250:257] for r in B[874:881]]

[array([255, 255, 255,  89,  89,  89,  89]),
 array([255, 255, 255,  89,  89,  89,  89]),
 array([255, 255, 255,  89,  89,  89,  89]),
 array([255, 255, 255,  89,  89,  89,  89]),
 array([255, 255, 255, 255, 255, 255, 255]),
 array([255, 255, 255, 255, 255, 255, 255]),
 array([255, 255, 255, 255, 255, 255, 255])]

In [106]:
A[248][874]

255

In [3]:
import xlrd

In [22]:
A

array([[  0,   3,   3, ..., 255, 255, 255],
       [  3,   0,   1, ..., 255, 255, 255],
       [  3,   1,   0, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ...,   0,   6,   9],
       [255, 255, 255, ...,   6,   0,   9],
       [255, 255, 255, ...,   9,   9,   0]])

In [24]:
A.shape
B.shape

(1006, 1006)

In [26]:
A[0,1]

3